baseURL: "https://temucinsrgl.github.io/" 
title: Temucin Sarigul - Portfolio
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Games
          url: games/
          weight: 1 
        - name: Work Experiences
          url: work/
          weight: 2

params:
    description: "I am a Game Designer and Level Designer, and a graduate of Istanbul Bilgi University's Digital Game Design program."
    author: Temucin Sarigul
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: dark
    hideFooter: false
    disableThemeToggle: false
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Temucin Sarigul
          subtitle: "I am Temucin Sarigul, a Game and Level Designer with a degree in Digital Game Design from Istanbul Bilgi University. I see game design as a way to spark imagination and create meaningful shared experiences with players. My work focuses on designing levels and mechanics that are fun, immersive, and innovative. Alongside my technical expertise, I bring strong communication skills, adaptability, and a collaborative mindset, thriving in multidisciplinary teams to deliver impactful player experiences."
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: artstation
          url: https://temucinsarigul7.artstation.com/   
        - name: itchio1
          url: https://temutemu.itch.io/       
        - name: linkedin
          url: https://www.linkedin.com/in/temu%C3%A7in-sar%C4%B1g%C3%BCl-030141244/
        - name: Email
          url: mailto:temucin00@gmail.com

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Temucin Sarigul"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2